"""
Reporter — turns raw ScanResult lists into something readable.

Writes three files per scan: JSON for machines, Markdown for terminals,
and a dark-themed HTML dashboard with a donut chart and severity filter.
Duplicate findings (same param, same module, different URLs) get grouped
into a single row so the report doesn't drown in 400 identical SQLi lines.
"""
import json, time, os, re
from datetime import datetime
from collections import defaultdict

SEV_COLORS = {"CRITICAL":"#ff2d55","HIGH":"#ff6b35","MEDIUM":"#ffd60a","LOW":"#30d158","INFO":"#636366"}
SEV_EMOJI  = {"CRITICAL":"🔴","HIGH":"🟠","MEDIUM":"🟡","LOW":"🟢","INFO":"⚪"}


def _group_results(results):
    """
    Group duplicate findings:
      - Same module + same param → merge URLs into one row with count
      - Keeps CRITICAL/unique findings ungrouped
    Returns list of dicts with optional 'count' and 'urls' fields.
    """
    grouped = []
    buckets = defaultdict(list)

    for r in results:
        detail = str(r.get("detail", ""))
        mod    = r.get("module", "")
        sev    = r.get("severity", "")

        # Extract param= from detail for grouping key
        param_m = re.search(r'param=(\S+)', detail)
        param   = param_m.group(1) if param_m else ""

        # Group same module+param+severity — but not CRITICAL (always show individually)
        if param and sev != "CRITICAL":
            key = f"{mod}|{sev}|{param}"
            buckets[key].append(r)
        else:
            grouped.append(r)  # CRITICAL or no param — show raw

    for key, items in buckets.items():
        if len(items) == 1:
            grouped.append(items[0])
        else:
            # Merge: take first item, add count + url list
            base   = dict(items[0])
            urls   = []
            for it in items:
                d = str(it.get("detail",""))
                # Extract URL from detail
                url_m = re.search(r'https?://\S+', d)
                if url_m: urls.append(url_m.group(0))
            param_m = re.search(r'param=(\S+)', str(base.get("detail","")))
            param   = param_m.group(1) if param_m else "?"
            mod     = base.get("module","")
            # Build a clean grouped detail
            raw_payload = (items[0].get("payload","") or
                           items[0].get("extra",{}).get("payload","") or
                           items[0].get("extra",{}).get("raw_payload",""))
            hint = raw_payload[:40] if raw_payload else _payload_hint(str(items[0].get("detail","")))
            base["detail"] = f"param={param} ({len(items)} URLs) — {hint}"
            base["count"]   = len(items)
            base["urls"]    = urls[:10]
            grouped.append(base)

    # Re-sort by severity order
    SEV_ORDER = {"CRITICAL":0,"HIGH":1,"MEDIUM":2,"LOW":3,"INFO":4}
    grouped.sort(key=lambda r: SEV_ORDER.get(r.get("severity","INFO"), 5))
    return grouped


def _payload_hint(detail: str) -> str:
    """Extract payload= or first meaningful token from a detail string."""
    m = re.search(r'payload=(\S+)', detail)
    if m: return m.group(1)[:40]
    m = re.search(r'db=(\S+)', detail)
    if m: return f"db={m.group(1)}"
    return detail[:40]


def to_markdown(results, meta):
    now    = datetime.fromtimestamp(meta.get("timestamp", time.time()))
    target = meta.get("target", "N/A")
    dur    = meta.get("duration", 0)
    grouped = _group_results(results)

    lines = [
        "# ⚡ LightScan v2.0 PHANTOM — Scan Report",
        f"> **Target:** `{target}`  ",
        f"> **Date:** {now.strftime('%Y-%m-%d %H:%M:%S')}  ",
        f"> **Duration:** {dur:.2f}s  ",
        f"> **Findings:** {len(results)} ({len(grouped)} grouped)",
        "", "---", "",
    ]

    for sev in ("CRITICAL","HIGH","MEDIUM","LOW","INFO"):
        group = [r for r in grouped if r.get("severity") == sev]
        if not group: continue
        lines.append(f"## {SEV_EMOJI.get(sev,'')} {sev} ({len(group)})")
        lines.append("| Module | Target | Port | Detail |")
        lines.append("|--------|--------|------|--------|")
        for r in group:
            det = str(r.get("detail","")).replace("|","\\|")
            cnt = r.get("count","")
            cnt_str = f" `×{cnt}`" if cnt else ""
            lines.append(
                f"| `{r.get('module','')}` | `{r.get('target','')}` "
                f"| `{r.get('port','')}` | {det}{cnt_str} |"
            )
            # Show URL list for grouped findings
            for url in r.get("urls",[]):
                lines.append(f"|  |  |  | ↳ `{url}` |")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by LightScan v2.0 PHANTOM — Developer: Light (Neok1ra)*")
    return "\n".join(lines)


def to_html(results, meta):
    now     = datetime.fromtimestamp(meta.get("timestamp", time.time()))
    target  = meta.get("target", "N/A")
    dur     = meta.get("duration", 0)
    grouped = _group_results(results)

    crit = sum(1 for r in results if r.get("severity") == "CRITICAL")
    high = sum(1 for r in results if r.get("severity") == "HIGH")
    med  = sum(1 for r in results if r.get("severity") == "MEDIUM")
    low  = sum(1 for r in results if r.get("severity") == "LOW")
    info = sum(1 for r in results if r.get("severity") == "INFO")
    total = len(results)

    # Build rows grouped by severity
    rows = ""
    for sev_order in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
        for r in grouped:
            if r.get("severity") != sev_order:
                continue
            sev = r.get("severity", "INFO")
            col = SEV_COLORS.get(sev, "#636366")
            mod = r.get("module", "")
            tgt = r.get("target", "")
            prt = str(r.get("port", ""))
            det = str(r.get("detail", "")).replace("<", "&lt;").replace(">", "&gt;")
            cnt = r.get("count", "")
            cnt_badge = (f'<span class="badge">×{cnt}</span> ') if cnt else ""
            url_rows = ""
            for url in r.get("urls", []):
                url_esc = url.replace("<", "&lt;").replace(">", "&gt;")
                url_rows += (f'<tr class="url-row"><td colspan="2"></td>'
                             f'<td colspan="4">↳ <a href="{url_esc}">{url_esc}</a></td></tr>')
            rows += (f'<tr>'
                     f'<td><span class="sev-badge" style="background:{col}">{sev}</span></td>'
                     f'<td><code>{mod}</code></td>'
                     f'<td class="mono">{tgt}</td>'
                     f'<td class="mono">{prt}</td>'
                     f'<td class="detail">{cnt_badge}{det}</td>'
                     f'</tr>{url_rows}')

    # Donut chart data
    chart_data = f"[{crit},{high},{med},{low+info}]"
    chart_colors = '["#ff2d55","#ff6b35","#ffd60a","#636366"]'
    chart_labels = '["CRITICAL","HIGH","MEDIUM","LOW/INFO"]'

    # Module breakdown
    module_counts = {}
    for r in results:
        m = r.get("module", "unknown")
        module_counts[m] = module_counts.get(m, 0) + 1
    module_rows = ""
    for mod, count in sorted(module_counts.items(), key=lambda x: -x[1]):
        pct = int((count / total * 100)) if total else 0
        module_rows += (f'<div class="mod-row">'
                        f'<span class="mod-name"><code>{mod}</code></span>'
                        f'<span class="mod-bar-wrap">'
                        f'<span class="mod-bar" style="width:{pct}%"></span>'
                        f'</span>'
                        f'<span class="mod-count">{count}</span>'
                        f'</div>')

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>LightScan — {target}</title>
<style>
  :root {{
    --bg: #0a0a0a;
    --surface: #141414;
    --surface2: #1e1e1e;
    --border: #2a2a2a;
    --red: #ff2d55;
    --orange: #ff6b35;
    --yellow: #ffd60a;
    --text: #e0e0e0;
    --muted: #666;
    --font: 'Courier New', Consolas, monospace;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: var(--bg); color: var(--text); font-family: var(--font);
          padding: 2rem; max-width: 1400px; margin: 0 auto; }}

  /* Header */
  .header {{ margin-bottom: 2rem; border-bottom: 1px solid var(--border); padding-bottom: 1.5rem; }}
  .logo {{ color: var(--red); font-size: 1.4rem; font-weight: bold;
           letter-spacing: .15em; margin-bottom: .3rem; }}
  .tagline {{ color: var(--muted); font-size: .72rem; letter-spacing: .08em; }}
  .meta {{ display: flex; gap: 2rem; margin-top: 1rem; flex-wrap: wrap; }}
  .meta-item {{ font-size: .78rem; }}
  .meta-item span {{ color: var(--muted); }}
  .meta-item strong {{ color: var(--red); }}

  /* Dashboard grid */
  .dashboard {{ display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 1.5rem;
                margin-bottom: 2rem; }}
  @media (max-width: 900px) {{ .dashboard {{ grid-template-columns: 1fr; }} }}

  /* Stat cards */
  .stats {{ display: grid; grid-template-columns: repeat(5, 1fr); gap: .8rem;
            background: var(--surface); border: 1px solid var(--border);
            border-radius: 8px; padding: 1.2rem; }}
  .stat {{ text-align: center; }}
  .stat-num {{ font-size: 2rem; font-weight: bold; line-height: 1; }}
  .stat-label {{ color: var(--muted); font-size: .62rem; letter-spacing: .1em;
                 margin-top: .3rem; }}

  /* Chart card */
  .chart-card {{ background: var(--surface); border: 1px solid var(--border);
                 border-radius: 8px; padding: 1.2rem; }}
  .card-title {{ color: var(--muted); font-size: .68rem; letter-spacing: .1em;
                 margin-bottom: 1rem; }}
  .chart-wrap {{ display: flex; align-items: center; gap: 1.5rem; }}
  canvas {{ max-width: 120px; max-height: 120px; }}
  .legend {{ flex: 1; }}
  .legend-item {{ display: flex; align-items: center; gap: .5rem;
                  font-size: .72rem; margin-bottom: .4rem; }}
  .legend-dot {{ width: 10px; height: 10px; border-radius: 2px; flex-shrink: 0; }}
  .legend-count {{ margin-left: auto; color: var(--muted); }}

  /* Module breakdown */
  .modules-card {{ background: var(--surface); border: 1px solid var(--border);
                   border-radius: 8px; padding: 1.2rem; }}
  .mod-row {{ display: flex; align-items: center; gap: .8rem;
              font-size: .72rem; margin-bottom: .5rem; }}
  .mod-name {{ width: 160px; flex-shrink: 0; overflow: hidden;
               text-overflow: ellipsis; white-space: nowrap; }}
  .mod-bar-wrap {{ flex: 1; background: var(--surface2); border-radius: 3px;
                   height: 6px; overflow: hidden; }}
  .mod-bar {{ height: 100%; background: var(--red); border-radius: 3px;
              transition: width .3s; }}
  .mod-count {{ width: 30px; text-align: right; color: var(--muted); }}

  /* Table */
  .table-wrap {{ background: var(--surface); border: 1px solid var(--border);
                 border-radius: 8px; overflow: hidden; }}
  .table-header {{ display: flex; justify-content: space-between; align-items: center;
                   padding: .8rem 1rem; border-bottom: 1px solid var(--border); }}
  .table-title {{ color: var(--muted); font-size: .68rem; letter-spacing: .1em; }}
  .filter-wrap {{ display: flex; gap: .5rem; }}
  .filter-btn {{ background: var(--surface2); border: 1px solid var(--border);
                 color: var(--muted); font-family: var(--font); font-size: .65rem;
                 padding: .25rem .6rem; border-radius: 3px; cursor: pointer;
                 letter-spacing: .05em; transition: all .15s; }}
  .filter-btn:hover, .filter-btn.active {{ border-color: var(--red);
                                            color: var(--text); }}
  table {{ width: 100%; border-collapse: collapse; }}
  th {{ background: #111; color: var(--red); text-align: left;
        padding: .6rem 1rem; font-size: .68rem; letter-spacing: .1em;
        border-bottom: 1px solid var(--border); white-space: nowrap; }}
  td {{ padding: .5rem 1rem; font-size: .75rem; border-bottom: 1px solid var(--border);
        vertical-align: top; }}
  tr:hover td {{ background: #1a1a1a; }}
  tr.url-row td {{ padding: .2rem 1rem; border: none; }}
  tr.url-row a {{ color: var(--muted); font-size: .7rem; text-decoration: none; }}
  tr.url-row a:hover {{ color: var(--text); }}
  .mono {{ font-family: var(--font); color: #aaa; }}
  .detail {{ color: #bbb; word-break: break-all; }}
  code {{ color: #ff9f0a; background: #111; padding: .1rem .35rem;
          border-radius: 3px; font-size: .72rem; }}
  .sev-badge {{ padding: .18rem .5rem; border-radius: 3px; font-size: .62rem;
                font-weight: bold; color: #000; white-space: nowrap; }}
  .badge {{ background: #333; color: #ff9f0a; padding: .1rem .35rem;
            border-radius: 3px; font-size: .65rem; }}

  /* Footer */
  footer {{ margin-top: 2rem; text-align: center; color: var(--muted);
            font-size: .68rem; padding-top: 1rem;
            border-top: 1px solid var(--border); }}
</style>
</head>
<body>

<div class="header">
  <div class="logo">⚡ LIGHTSCAN v2.0-PHANTOM</div>
  <div class="tagline">ASYNC NETWORK RECON &amp; ATTACK FRAMEWORK · DEVELOPER: LIGHT (NEOK1RA)</div>
  <div class="meta">
    <div class="meta-item"><span>TARGET </span><strong>{target}</strong></div>
    <div class="meta-item"><span>DATE </span>{now.strftime('%Y-%m-%d %H:%M:%S')}</div>
    <div class="meta-item"><span>DURATION </span>{dur:.1f}s</div>
    <div class="meta-item"><span>FINDINGS </span>{total}</div>
  </div>
</div>

<!-- Stat cards -->
<div class="stats" style="margin-bottom:1.5rem">
  <div class="stat">
    <div class="stat-num">{total}</div>
    <div class="stat-label">TOTAL</div>
  </div>
  <div class="stat">
    <div class="stat-num" style="color:#ff2d55">{crit}</div>
    <div class="stat-label">CRITICAL</div>
  </div>
  <div class="stat">
    <div class="stat-num" style="color:#ff6b35">{high}</div>
    <div class="stat-label">HIGH</div>
  </div>
  <div class="stat">
    <div class="stat-num" style="color:#ffd60a">{med}</div>
    <div class="stat-label">MEDIUM</div>
  </div>
  <div class="stat">
    <div class="stat-num" style="color:#636366">{low+info}</div>
    <div class="stat-label">LOW/INFO</div>
  </div>
</div>

<!-- Dashboard -->
<div class="dashboard">
  <div class="chart-card" style="grid-column: span 1">
    <div class="card-title">SEVERITY BREAKDOWN</div>
    <div class="chart-wrap">
      <canvas id="donut" width="120" height="120"></canvas>
      <div class="legend">
        <div class="legend-item">
          <div class="legend-dot" style="background:#ff2d55"></div>
          CRITICAL <span class="legend-count">{crit}</span>
        </div>
        <div class="legend-item">
          <div class="legend-dot" style="background:#ff6b35"></div>
          HIGH <span class="legend-count">{high}</span>
        </div>
        <div class="legend-item">
          <div class="legend-dot" style="background:#ffd60a"></div>
          MEDIUM <span class="legend-count">{med}</span>
        </div>
        <div class="legend-item">
          <div class="legend-dot" style="background:#636366"></div>
          LOW/INFO <span class="legend-count">{low+info}</span>
        </div>
      </div>
    </div>
  </div>

  <div class="modules-card" style="grid-column: span 2">
    <div class="card-title">FINDINGS BY MODULE</div>
    {module_rows}
  </div>
</div>

<!-- Findings table -->
<div class="table-wrap">
  <div class="table-header">
    <div class="table-title">FINDINGS</div>
    <div class="filter-wrap">
      <button class="filter-btn active" onclick="filterTable('ALL')">ALL</button>
      <button class="filter-btn" onclick="filterTable('CRITICAL')" style="color:#ff2d55">CRIT</button>
      <button class="filter-btn" onclick="filterTable('HIGH')" style="color:#ff6b35">HIGH</button>
      <button class="filter-btn" onclick="filterTable('MEDIUM')" style="color:#ffd60a">MED</button>
      <button class="filter-btn" onclick="filterTable('LOW')">LOW</button>
    </div>
  </div>
  <table id="findings-table">
    <thead>
      <tr>
        <th>SEV</th>
        <th>MODULE</th>
        <th>TARGET</th>
        <th>PORT</th>
        <th>DETAIL</th>
      </tr>
    </thead>
    <tbody id="findings-body">{rows}</tbody>
  </table>
</div>

<footer>
  LightScan v2.0-PHANTOM · Developer: Light (Neok1ra) · github.com/ne0k1r4
</footer>

<script>
// Donut chart
(function() {{
  const data   = {chart_data};
  const colors = {chart_colors};
  const labels = {chart_labels};
  const canvas = document.getElementById('donut');
  if (!canvas) return;
  const ctx = canvas.getContext('2d');
  const total = data.reduce((a, b) => a + b, 0);
  if (total === 0) return;
  let start = -Math.PI / 2;
  const cx = canvas.width / 2, cy = canvas.height / 2;
  const r = 48, inner = 30;
  data.forEach((val, i) => {{
    if (val === 0) return;
    const angle = (val / total) * Math.PI * 2;
    ctx.beginPath();
    ctx.moveTo(cx, cy);
    ctx.arc(cx, cy, r, start, start + angle);
    ctx.closePath();
    ctx.fillStyle = colors[i];
    ctx.fill();
    start += angle;
  }});
  // Inner circle (donut hole)
  ctx.beginPath();
  ctx.arc(cx, cy, inner, 0, Math.PI * 2);
  ctx.fillStyle = '#141414';
  ctx.fill();
  // Center text
  ctx.fillStyle = '#e0e0e0';
  ctx.font = 'bold 18px Courier New';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText(total, cx, cy);
}})();

// Table filter
function filterTable(sev) {{
  document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
  event.target.classList.add('active');
  const rows = document.querySelectorAll('#findings-body tr:not(.url-row)');
  rows.forEach(row => {{
    const badge = row.querySelector('.sev-badge');
    if (!badge) return;
    const rowSev = badge.textContent.trim();
    row.style.display = (sev === 'ALL' || rowSev === sev) ? '' : 'none';
  }});
}}
</script>
</body>
</html>"""


class Reporter:
    def __init__(self, output_dir="."):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def save(self, results, meta, basename="lightscan_report"):
        raw = [r.to_dict() if hasattr(r,"to_dict") else r for r in results]
        jp  = os.path.join(self.output_dir, f"{basename}.json")
        mp  = os.path.join(self.output_dir, f"{basename}.md")
        hp  = os.path.join(self.output_dir, f"{basename}.html")
        with open(jp,"w") as f: json.dump({"meta":meta,"results":raw}, f, indent=2)
        with open(mp,"w") as f: f.write(to_markdown(raw, meta))
        with open(hp,"w") as f: f.write(to_html(raw, meta))
        print(f"\n\033[38;5;196m[REPORT]\033[0m ↳ JSON: {jp}")
        print(f"\033[38;5;196m[REPORT]\033[0m ↳ MD:   {mp}")
        print(f"\033[38;5;196m[REPORT]\033[0m ↳ HTML: {hp}")
        return jp, mp, hp
